# Magma emplacement: discrete sills, the smeared Q_magma source, and the advection they drive.

"""
    mean_sill_velocity(z, ȧ, zbot, ztop; r=5e3)

Time-averaged host-rock velocity generated by sills whose centers are uniformly distributed
between `zbot` and `ztop`.

Each sill has full aperture `d`, so each wall moves by `d/2`; the event rate `ȧ/d` cancels
`d` from the mean. Elastic decay as in [`crack_perp_displacement`](@ref).
"""
function mean_sill_velocity(z, ȧ, zbot, ztop; r = 5.0e3, ν = 0.3)
    ȧ >= 0 || throw(ArgumentError("ȧ must be nonnegative"))
    ztop > zbot || throw(ArgumentError("ztop must be greater than zbot"))
    # the analytic primitive below is indeterminate for an unbounded crack, so the uniform
    # opening limit insert_sill accepts at r = Inf has no counterpart here
    (r > 0 && isfinite(r)) || throw(ArgumentError("r must be positive and finite"))

    H = ztop - zbot
    return (ȧ / (2H)) .* (crack_perp_integral.(z .- zbot, r, ν) .- crack_perp_integral.(z .- ztop, r, ν))
end

"""
    compute_Q_magma!(Params, MatParam, z; Tsill, ȧ, Silltop, Sillbot, r=5e3)

Smear repeated sill injection into a steady volumetric heat source `Params.Q` [W/m^3],

    Q_magma(z,t) = ρₘ ȧ/H [ cp(Tₘ - T(z,t)) + L(1-ϕ(T)) ]

over the injection zone between depths `Silltop` and `Sillbot` [km] of thickness `H`, zero
elsewhere.

`ȧ` is the step-mean accretion rate [m/s] **on the axis**, where the crack is thickest - the
full aperture per unit time, the same quantity `insert_sill` delivers as `Sill_thick` per
event. A magma supply given as a volume rate becomes `ȧ` by dividing by
[`lateral_effective_area`](@ref), not by `πR²`.

The first term is sensible heat surrendered cooling from `Tsill` to the local temperature,
the second latent heat released crystallizing from ϕ=1 down to the local ϕ(T). ρ, cp and ϕ
are evaluated from `Params.Told`, as the rest of the residual is linearized.

ρₘ is the host-rock thermal density of `MatParam`, not the melt density
`EruptionParams.ρ_melt`: an approximation at the ~10% level of the injected heat.

Also sets `Params.w` to the ensemble-mean host-rock velocity of sills with uniformly
distributed centers in the zone, using the same elastic displacement profile and
full-aperture convention as [`insert_sill`](@ref).
"""
function compute_Q_magma!(Params, MatParam, z; Tsill, ȧ, Silltop, Sillbot, r = 5.0e3, ν = 0.3)
    all(isfinite, (Tsill, ȧ, Silltop, Sillbot, r)) ||
        throw(ArgumentError("source parameters must be finite"))
    ȧ >= 0 || throw(ArgumentError("ȧ must be nonnegative"))
    Sillbot > Silltop || throw(ArgumentError("Sillbot must be greater than Silltop"))
    r > 0 || throw(ArgumentError("r must be positive"))

    zbot, ztop = -Sillbot * 1.0e3, -Silltop * 1.0e3
    first(z) <= zbot < ztop <= last(z) || throw(
        ArgumentError(
            "injection zone [$zbot, $ztop] m must lie inside [$(first(z)), $(last(z))] m"
        )
    )

    args = (T = Params.Told .+ 273.15,)
    compute_heatcapacity!(Params.Cp, MatParam, Params.Phases, args)
    compute_density!(Params.ρ, MatParam, Params.Phases, args)
    compute_meltfraction!(Params.ϕ, MatParam, Params.Phases, args)

    Q_L = NumValue(MatParam[1].LatentHeat[1].Q_L)
    H = (Sillbot - Silltop) * 1.0e3

    Params.Q .= 0.0
    # Overlap widths sum to `H` by construction, so ∑ Q Δz = ρₘ ȧ [...] exactly whatever the
    # alignment - the discrete form of the ∫Q dz the smearing is defined by - and interior
    # cells of a well-resolved zone still get the full ρₘ ȧ/H [...].
    widths = interval_cell_widths(z, zbot, ztop)
    cells = diff(grid_cell_edges(z))
    ind = findall(>(0.0), widths)
    isempty(ind) && throw(ArgumentError("injection zone contains no grid points"))
    Params.Q[ind] .= (widths[ind] ./ cells[ind]) .* Params.ρ[ind] .* (ȧ / H) .* (Params.Cp[ind] .* (Tsill .- Params.Told[ind]) .+ Q_L .* (1.0 .- Params.ϕ[ind]))

    Params.w .= mean_sill_velocity(z, ȧ, zbot, ztop; r, ν)

    return Params.Q
end

"""
    crack_perp_shape(z, r, ν) -> [-]

On-axis wall displacement of a pressurised penny-shaped crack of radius `r` in an elastic
medium (Sun 1969), normalised to one at the crack face. `ν` is Poisson's ratio; the elastic
moduli and the overpressure cancel under that normalisation, so the shape depends only on
`z/r` and `ν`.

The crack opens as [`lateral_profile`](@ref) and so displaces
`lateral_effective_area(r)` times its axial aperture - the same body the lateral heat loss
and the 2-D/3-D export describe, and the `Q = 2πHW²/3` convention of the penny-shaped sills
in InjectSills.jl and MagmaThermoKinematics.jl.
"""
function crack_perp_shape(z, r, ν)
    isinf(r) && return one(z / oneunit(z))   # unbounded crack: uniform opening at every depth
    t = abs(z)
    moment = t * atan(r / t)                 # t*atan(r/t) -> 0 at the face, -> r far away
    return (r - moment + (moment - r * t^2 / (t^2 + r^2)) / (2 * (1 - ν))) / r
end

"""
    crack_perp_integral(z, r, ν) -> [m]

`∫₀^|z| crack_perp_shape(s, r, ν) ds`, the antiderivative [`mean_sill_velocity`](@ref) needs
to average the opening of sills whose centres are spread over an interval. Even in `z`, so
it is the primitive of the (odd) displacement field.
"""
function crack_perp_integral(z, r, ν)
    t = abs(z)
    isinf(r) && return t
    I = t^2 / 2 * atan(r / t) + (r / 2) * (t - r * atan(t / r))
    return (r * t - I + (I - r * t + r^2 * atan(t / r)) / (2 * (1 - ν))) / r
end

"""
    crack_perp_displacement(z, d; r=5e3, ν=0.3)

Wall displacement at perpendicular distance `z` from the plane of a penny-shaped crack of
radius `r` opening by an axial aperture `2d`: `d` at the face, decaying to zero far away,
with the shape [`crack_perp_shape`](@ref). `r = Inf` opens uniformly at every depth.

Opens a sill ([`insert_sill`](@ref)) and closes an erupted band
([`collapse_displacement`](@ref)).
"""
crack_perp_displacement(z, d; r = 5.0e3, ν = 0.3) = d .* crack_perp_shape.(z, r, ν)

"""
    T_adv, rock_adv, h_out = insert_sill(T, rocks, z; Sill_thick=400, Sill_z0=-20e3, Sill_T=1200, SillType=:elastic, r=5e3)

Add a sill of thickness `Sill_thick` centered at `Sill_z0`: the temperature field `T` and
the injected-magma indicator `rocks` on grid `z` are advected apart to make room, then the
sill interval is control-volume mixed at `Sill_T` and given its `Sill_phase` content.

`SillType` sets the displacement: `:constant` moves the rocks above and below rigidly,
`:elastic` decays it with distance over the crack radius `r`.

`r` is the crack radius and `ν` Poisson's ratio of the host rock: the same crack that sets
the lateral heat loss and the 2-D/3-D expansion ([`lateral_profile`](@ref)), so the three
describe one body. `r = Inf` opens the sill uniformly at every depth, reproducing
`:constant`.

`h_out` is the injected-magma content [m] the displacement pushes out through a domain
boundary, the boundary term of the magma-volume budget ([`MassBudget`](@ref)).
"""
function insert_sill(T, rocks, z; Sill_thick = 400, Sill_z0 = -20.0e3, Sill_T = 1200, Sill_phase = 1.0, SillType = :elastic, r = 5.0e3, ν = 0.3)
    length(T) == length(rocks) == length(z) ||
        throw(DimensionMismatch("T, rocks, and z must have equal length"))
    all(isfinite, (Sill_thick, Sill_z0, Sill_T, Sill_phase)) ||
        throw(ArgumentError("sill parameters must be finite"))
    Sill_thick > 0 || throw(ArgumentError("Sill_thick must be positive"))
    r > 0 || throw(ArgumentError("r must be positive"))
    Sill_phase >= 0 || throw(ArgumentError("Sill_phase must be nonnegative"))
    SillType in (:constant, :elastic) ||
        throw(ArgumentError("SillType must be :constant or :elastic"))
    z_lo, z_hi = Sill_z0 - Sill_thick / 2, Sill_z0 + Sill_thick / 2
    first(z) <= z_lo < z_hi <= last(z) || throw(
        ArgumentError(
            "sill interval [$z_lo, $z_hi] m must lie inside [$(first(z)), $(last(z))] m"
        )
    )

    # find points above & below sill emplacement level
    z_shift = Vector(z) .- Sill_z0
    Displ = zero(z_shift)

    # shift points above
    id_above = findall(z_shift .> 0)
    id_below = findall(z_shift .< 0)

    # Assume constant displacement - in elastic case this should decrease with distance from sill
    if SillType == :constant
        Displ[id_above] .= Sill_thick / 2
        Displ[id_below] .= -Sill_thick / 2
    elseif SillType == :elastic
        Displ[id_above] .= crack_perp_displacement(z_shift[id_above], Sill_thick / 2; r, ν)
        Displ[id_below] .= -crack_perp_displacement(z_shift[id_below], Sill_thick / 2; r, ν)
    end

    T_adv = semilagrangian_advection(T, Displ, z)

    # Mix the new sill into each overlapped control volume. This remains defined when a
    # sill is thinner than the grid spacing or falls between nodes.
    edges = grid_cell_edges(z)
    sill_widths = interval_cell_widths(z, z_lo, z_hi)
    sill_fraction = sill_widths ./ diff(edges)
    T_adv .= (1 .- sill_fraction) .* T_adv .+ sill_fraction .* Sill_T

    # move host rock and previously injected material with the same (elastic or constant)
    # displacement as T. The indicator stores injected-magma content per grid control volume;
    # values can exceed one where emplacement compresses previously injected material.
    rock_adv = conservative_advection(rocks, Displ, z)
    h_out = nonnegative_debit(
        integrated_content(rocks, z),
        integrated_content(rock_adv, z), "injected-magma content"; ncells = length(z)
    )
    add_uniform_content!(rock_adv, z, z_lo, z_hi, Sill_phase * Sill_thick)

    return T_adv, rock_adv, h_out
end

"""
    Tadv = semilagrangian_advection(T, Displ, z)

Advect `T` by displacing the grid (`z_new = z + Displ`) and sampling a linear interpolant
built there back onto `z`. Not conservative; see [`conservative_advection`](@ref).
"""
function semilagrangian_advection(T, Displ, z)

    z_new = z + Displ # advect grid
    all(>(0), diff(z_new)) ||
        throw(ArgumentError("displacement folds the grid; advected coordinates must be strictly ascending"))
    interp_linear = linear_interpolation(z_new, T)
    T_adv = interp_linear.(z)

    return T_adv
end

"""
    conservative_advection(field, Displ, z)

Finite-volume (mass-conserving) advection of a per-cell `field` by the displacement
`Displ` [m] on grid `z`. Unlike [`semilagrangian_advection`](@ref) — which
interpolates the *value* and lets integrated content drift wherever the displacement
stretches or compresses the grid — this moves each control volume's content: cell
edges are displaced (Displ interpolated to the edges) and every parcel deposits its
conserved content onto the fixed cells it overlaps. [`integrated_content`](@ref) is preserved exactly
(up to parcels pushed past the domain boundary).

Use this for the injected-rock phase indicator, whose integral is the injected crust
thickness: repeated non-conservative advection erodes thin grey bands (a one-way loss
of ~2-3% per injection). Temperature keeps using `semilagrangian_advection` — an
intensive field where the stretch-induced drift is small and expected.
"""
function conservative_advection(field, Displ, z)
    length(field) == length(Displ) == length(z) ||
        throw(DimensionMismatch("field, Displ, and z must have equal length"))
    all(isfinite, field) && all(isfinite, Displ) ||
        throw(ArgumentError("field and Displ must be finite"))
    n = length(z)
    ze = grid_cell_edges(z)
    widths = diff(ze)
    de = linear_interpolation(z, Displ; extrapolation_bc = Line()).(ze)
    xe = ze .+ de
    all(>(0), diff(xe)) ||
        throw(ArgumentError("displacement folds a control volume; displaced edges must be strictly ascending"))
    out = zeros(promote_type(eltype(field), eltype(ze)), n)
    for j in 1:n
        L, R = xe[j], xe[j + 1]
        w = R - L
        density = field[j] * widths[j] / w
        i1 = clamp(searchsortedlast(ze, L), 1, n)
        i2 = clamp(searchsortedfirst(ze, R) - 1, 1, n)
        for i in i1:i2
            ov = min(R, ze[i + 1]) - max(L, ze[i])
            ov > 0 && (out[i] += density * ov / widths[i])
        end
    end
    return out
end
"""
    advect_w!(Params)

Semi-Lagrangian advection of `Params.Told` by the vertical velocity field `Params.w`
[m/s] over one timestep `Params.Δt`, using the same `semilagrangian_advection` scheme
as discrete sill injection (`insert_sill`). Mimics the host-rock displacement caused by
continuous magma accretion (e.g. as set by `compute_Q_magma!`) in a way consistent with
how discrete sills displace the column, rather than via an upwind advection term in the
residual.
"""
function advect_w!(Params)
    Displ = Params.w .* Params.Δt
    Params.Told .= semilagrangian_advection(Params.Told, Displ, Params.z)
    return Params.Told
end

"""
    advect_markers!(markers, Params)

Advance a vector of passive marker depths `markers` [m] by one timestep using the
host-rock advection velocity `Params.w` [m/s], interpolated onto the (possibly
off-grid) marker positions. Used to visualize how far host rock outside the
injection zone has moved under `compute_Q_magma!`/`advect_w!`, analogous to the
`rocks` field tracked for discrete sill injection.
"""
function advect_markers!(markers, Params)
    w_interp = linear_interpolation(Params.z, Params.w; extrapolation_bc = Line())
    markers .+= w_interp.(markers) .* Params.Δt
    return markers
end
